
# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

name: observability-learning
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

cloud.id: My_deployment:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyQ5MWZhYzMyNTllMjY0NjdmYjU5OGFhMmQxZGQ3NTljNSQzYWU3ODEyODFjMjk0ZTE5ODE2YTIyZGQ3YzY3MzdhZQ==
cloud.auth: elastic:QFVxMim9Z1dmEki9mfm2Qxc7  

output.elasticsearch:
  pipeline: "pipeline-adatech"

logging.level: debug
logging.json: true
logging.selectors: ["*"] 